### ISSUE TITLE
Update jQuery

### ISSUE THREAD

**Issue by mazzcris** [sortello/sortello#74]
jQuery should be updated to 3.0.0 or higher

**Comment by cfsbsi** [comment]
Can I do that?

**Comment by cfsbsi** [comment]
I need some help

I update the jQuery, but I will test with E2E tests, but I'm having a problem, the tests are stopping on 
`let allLabel = element(by.css('.label__item.label__none'));
    browser.wait(EC.presenceOf(allLabel), 20000).then(function () {
      allLabel.click();
      nextChoice();
    })`

I'm think that I should setup something on my trello.
Also to know `testTrelloExtId` on protractor.conf.js is just the id of trello task?

**Comment by mazzcris** [comment]
That part should be documented more, extId should be the ID of one card from the list you want to sort. Don't worry about the E2E tests, I will check and fix them if needed before deploying the latest updates. Thank you @cfsbsi!

**Comment by cfsbsi** [comment]
done on #79 if need something else, please let me know

**Comment by mazzcris** [comment]
Closing this, thank you @cfsbsi
